site_name: Yappes Enterprise Documentation
site_url: http://docs.enterprise.yappes.com/
theme:
  name: material
  logo: images/title_logo.png
nav:
  - Home: index.md
  - 'Onboard Existing API':
    - add_api.md
    - api_details.md
    - environment.md
    - route_map.md
    - tags.md
    - resource.md
    - add_endpoint.md
    - add_multiple_endpoint.md
    - add_authentication.md
    - previewAPI.md
    - pricing.md
    - quota.md
    - license.md
    - about.md
    - security.md
    - delete_api.md
    - change_api_ownership.md
  - 'Create New API':
    - create_new_api.md
    - api_details_new.md
    - environment_new.md
    - tags_new.md
    - 'Managing Endpoints':
      - resource_new.md
      - create_endpoint.md
      - add_logic.md
      - endpoint_documentation.md
      - testing_endpoint.md
    - 'Remote Sources':
      - remote_sources.md
      - update_remote_sources.md
    - 'Error Settings':
      - error_settings.md
      - configure_error_settings.md
    - pricing_new.md
    - Quota_new.md
    - license_new.md
    - about_new.md
    - security_new.md
  -  publish_api.md
  - 'Consume an API':
    - consume_api.md
    - consume_filter_api.md
    - discover_search_api.md
    - consume_apiview_docum.md
  - dashboard.md
  - 'Applications':
    - add_application.md
    - application_details.md
    - application_keys.md
    - application_apis.md
  - 'Deal Room':
    - managedeals.md
    - managedeals_provider.md
    - managedeals_consumer.md
  - 'API Subscriptions':
    - subscriptions.md
    - start_stop_subscriptions.md
    - manage_subscription_details.md
    - subscription_manage_environment_access.md
  - 'Rate APIs':
    - rate_my_subscribed_api.md
    - reviewRatingsProvider.md
  - 'User Profile':
    - intro_profile.md
    - loggeduser_profile.md
    - apiprovider_profile.md
    - preferences.md
    - billing.md
    - manageInvoice.md
  - 'Follow/Unfollow API': 'follow_unfollow_api.md'
  - 'Manage Votes API': 'vote_cancelvote_api.md'
  - 'Manage Collections And Objects':
    - CollectionsAndObjects/manage_collections_and_objects.md
    - 'Create/Update Collection': CollectionsAndObjects/create_update_delete_collection.md
    - 'Create/Update Objects': CollectionsAndObjects/create_update_delete_object.md
  - 'Report An API': 'reportAPI.md'
  - 'My API Subscriptions': 'MyApiSubscriptions/my_api_subscriptions.md'
  - 'API Analytics Providers':
    - 'API Analytics': APIAnalytics/api_analytics.md
    - 'API Level': APIAnalytics/analytics_api_level.md
    - 'Endpoint Level': APIAnalytics/analytics_endpoint_level.md
    - 'User Level': APIAnalytics/analytics_user_level.md
  - 'API Analytics Consumers':
    - 'API Analytics Consumer': APIAnalytics/APIAnalytics_consumers.md
    - 'API Level': APIAnalytics/analytics_consumer_apilevel.md
# plugroute_:
#   - search
 #   - awesome-pages
